echo "os version: `uname -o`"
echo "release no: `uname -r`"
echo "kernel version: `uname -v`"
echo "mouse settings : `xinput --list-props "PixArt USB Optical Mouse"`"

echo "available shells : `cat /etc/shells`"
echo "processor : `uname -p`"
echo "harddisk info: `lsblk`"
echo "memory info : `cat /proc/meminfo`"
echo "filebsystem :`df -k`"
